### ISSUE TITLE
Fix Comments Page CSS

### ISSUE THREAD

**Issue by nmtry** [xlab-classes/cse442-spring2022-team-the-howdies#24]
Task tests: 

Test 1:
1. Visit [Website](https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442w/cse442-spring2022-team-the-howdies/ratemyclassPHP/index.php)
2. Go to [Login Page](https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442w/cse442-spring2022-team-the-howdies/ratemyclassPHP/login.php) and login with the following information:
- uat_user@gmail.com
- testing123@
3. Enter "university at buffalo" into the university search and click search
4. Once you are on the view classes page, click on a class (preferably one with a

**Comment by jadonner** [comment]
Task Test

1. Navigate to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442w/cse442-spring2022-team-the-howdies/ratemyclassPHP/index.php
2. Click Login at the top right
3. When taken to the login page, login with your own account's credentials
4. When taken back to the Homepage, type "University at Buffalo" into the University Name and click search
5.  Find the class "CSE 115" and click on it
6. When taken to the reviews page, find any review and click the "Comment" button
7. Verify that the page shows up properly and reflects CSS changes
